### ISSUE TITLE
Compile error from external RPLidar library (ver 2.0)

### ISSUE THREAD

**Issue by SimoneMic** [robotology/yarp-device-rplidar#1]
Trying to compiling the repo I get an error related to the external SDK library (ver 2.0).

### Error Message:
```
/home/user1/yarp-device-rplidar/extern/rplidar_20/sdk/src/arch/linux/net_socket.cpp: In member function ‘virtual u_result rp::net::SocketAddress::getAddressAsString(char*, size_t) const’:
/home/user1/yarp-device-rplidar/extern/rplidar_20/sdk/src/arch/linux/net_socket.cpp:170:15: error: ordered comparison of pointer with integer zero (‘const char*’ and ‘int’)
  170 |     return ans<=0?RESULT_OPERATION_FAIL:RESULT_OK;
      |            ~~~^~~
```
### Proposed Solution
I have modified the code in the `yarp-device-rplidar/extern/rplidar_20/sdk/src/arch/linux/net_socket.cpp` file as below and it compiles.

```
u_result SocketAddress::getAddressAsString(char * buffer, size_t buffersize) const
{
    int net_family = reinterpret_cast<const sockaddr_storage *>(_platform_data)->ss_family;
    const char *ans = NULL;
    switch (net_family) {
        case AF_INET:
            ans = inet_ntop(net_family, &reinterpret_cast<const sockaddr_in *>(_platform_data)->sin_addr,
                            buffer, buffersize);
        break;

        case AF_INET6:
            ans = inet_ntop(net_family, &reinterpret_cast<const sockaddr_in6 *>(_platform_data)->sin6_addr,
                            buffer, buffersize);

        break;
    }
    //return ans<=0?RESULT_OPERATION_FAIL:RESULT_OK; -> not working code changed in the "if" below
    if (ans==NULL)
    {
        return RESULT_OPERATION_FAIL;
    }
    return RESULT_OK;
}
```

From [this link](https://man7.org/linux/man-pages/man3/inet_ntop.3.html) i got the reference for the `inet_ntop` function: "returns a non-null pointer to dst.  NULL
       is returned if there was an error, with [errno](https://man7.org/linux/man-pages/man3/errno.3.html) set to indicate the
       error."

**Comment by pattacini** [comment]
Hi @randaz81 @elandini84

Any news about this issue?
I have been lately integrating this device into a CI/dry-run.
However, I had to comment it out because of this compilation error.

cc @SimoneMic

**Comment by randaz81** [comment]
The bug is in the vendor SDK.
Maybe it has been fixed upstream by https://github.com/Slamtec/rplidar_sdk/commit/45431f11f64acf8cc145df84b1b61e9d45d0029b but it is not yet officially released.

It also seems that Slamtec is not providing new releases actively (the last one is from 2021), so I'll go for a local modification on our local copy (i.e. extern/rplidar_20)

**Comment by pattacini** [comment]
>so I'll go for a local modification on our local copy (i.e. extern/rplidar_20)

Hi @randaz81 
Do you have news about that?

**Comment by martinaxgloria** [comment]
Hi @randaz81, any news about this issue?

**Comment by randaz81** [comment]
fixed by https://github.com/robotology/yarp-device-rplidar/pull/5
