### ISSUE TITLE
Support for Ubuntu 20.04 - revert CMake Minimum Requirement back to 16.3 in `CMakeLists.txt`

### ISSUE THREAD

**Issue by SimoneMic** [robotology/yarp-device-rplidar#4]
With the [new update to YARP 3.9](https://github.com/robotology/yarp-device-rplidar/commit/04c7cde904d8f2a07ea78ba87fcc06cc89c85ee0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL7) the CMake Minimum required has been bumped to 3.17. 
This creates issues with the robots that are running Lidars with OS Ubuntu 20.04, i.e. `ergoCubSN000` and `ergoCubSN001`, since in Ubuntu20.04 the CMake version of the released packages is 3.16.3 (devel).

These robots would need to revert to YARP 3.8.x, or to manually update CMake.

I have manually reverted the CMake Minimum Requirement to 3.16.3 in `CMakeLists.txt` and it compiles properly.
If there aren't any explicit motivations to have CMake to 3.17, I'd keep it to the previous version, to keep backward compatibility.

**Comment by randaz81** [comment]
No, you have to manually download Cmake 3.17 from the website (https://github.com/Kitware/CMake/releases/tag/v3.17.3) and install it on your Ubuntu 20.04.
Please do not manually edit CMakeLists.txt!!

Please also note that the yarp 3.10 will require cmake>3.19 and that Ubuntu 22.04 is shipped with cmake > 3.22

**Comment by traversaro** [comment]
Another way of getting modern CMake versions on Ubuntu 20.04 is to use the Kitware apt repo at https://apt.kitware.com/ 
.
